[package]
name = "cassetter"
version = "0.0.0"
edition = "2021"

[lib]
name = "_core"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.28", features = ["extension-module"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_yaml = "0.9"
flate2 = "1"
brotli = "8"
zstd = "0.13"
regex = "1"
unicode-normalization = "0.1"
pythonize = "0.28"
url = "2"
chrono = { version = "0.4", features = ["serde"] }
toml = "0.8"
