[package]
name = "cassetter-python"
description = "PyO3 bindings for cassetter-core."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lib]
name = "_core"
crate-type = ["cdylib"]

[dependencies]
cassetter-core.workspace = true
serde_json.workspace = true
pyo3 = { version = "0.29" }
pythonize = "0.29"

[lints]
workspace = true
